// <auto-generated />
using dotnet_server._Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotnet_server.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("dotnet_server._Models.Consultation", b =>
        {
            b.Property<Guid>("Id");
            b.Property<bool>("AgreedToTerms");
            b.Property<string>("Budget").HasMaxLength(120);
            b.Property<DateTimeOffset>("CreatedAt");
            b.Property<string>("Description").HasMaxLength(2000);
            b.Property<string>("Email").HasMaxLength(180);
            b.Property<string>("Name").HasMaxLength(120);
            b.Property<string>("PhoneNumber").HasMaxLength(40);
            b.Property<string>("Placement").HasMaxLength(120);
            b.Property<string>("PreferredArtist").HasMaxLength(120);
            b.Property<string>("Size").HasMaxLength(120);
            b.Property<string>("Style").HasMaxLength(120);
            b.Property<int>("Status");
            b.Property<Guid?>("TattooDealId");
            b.HasKey("Id");
            b.HasIndex("TattooDealId");
            b.ToTable("Consultations");
        });
    }
}
